{
 "title": "Suivi Aeronefs Monde Temps Reel",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "Position actuel des aéronefs",
   "type": "geomap",
   "gridPos": { "h": 18, "w": 18, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "select icao24, latitude, longitude\r\nfrom aeronefs a\r\nwhere id_insertion = (SELECT MAX(id_insertion) FROM aeronefs) \r\n\tand latitude is not null \r\n\tand longitude is not null;"
    }
   ]
  },
  {
   "title": "Diag circulaire types aeronefs",
   "type": "piechart",
   "gridPos": { "h": 12, "w": 6, "x": 18, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "allValues" ] } },
   "targets": [
    {
     "rawSql": "SELECT lib_category, count(*) as nb\r\nFROM aeronefs a\r\nLEFT JOIN category c on a.category = c.id_category\r\nWHERE id_insertion = (SELECT MAX(id_insertion) FROM aeronefs) \r\n\tAND latitude IS NOT NULL \r\n\tAND longitude IS NOT NULL\r\n\tAND a.category NOT IN (0,1)\r\nGROUP BY lib_category;"
    }
   ]
  },
  {
   "title": "Date de mesure",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT TO_CHAR(MAX(date_insertion), 'DD/MM/YYYY HH24:MI:SS') AS date\r\nFROM insertion;\r\n"
    }
   ]
  },
  {
   "title": "Nombre d'aéronefs",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select count(icao24)\r\nfrom aeronefs\r\nwhere id_insertion = (SELECT MAX(id_insertion) FROM aeronefs) \r\n\tand latitude is not null \r\n\tand longitude is not null;"
    }
   ]
  },
  {
   "title": "Moyenne alt baro",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select AVG(baro_altitude)\r\nfrom aeronefs\r\nwhere id_insertion = (SELECT MAX(id_insertion) FROM aeronefs) \r\n\tand latitude is not null \r\n\tand longitude is not null;"
    }
   ]
  },
  {
   "title": "V moyenne (km/h)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select AVG(velocity)*3.6\r\nfrom aeronefs\r\nwhere id_insertion = (SELECT MAX(id_insertion) FROM aeronefs) \r\n\tand latitude is not null \r\n\tand longitude is not null;"
    }
   ]
  }
 ]
}