{
 "title": "Suivi aéronef",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "var_icao24",
    "label": "icao24",
    "query": "select icao24\nfrom aeronefs a\nwhere time_position > TO_TIMESTAMP($__timeFrom(), 'YYYY-MM-DD\"T\"HH24:MI:SS.USSTZD')AT TIME ZONE 'UTC' + INTERVAL '4 hours'"
   }
  ]
 },
 "panels": [
  {
   "title": "Suivi aéronef | icao24 : $var_icao24",
   "type": "geomap",
   "gridPos": { "h": 17, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT latitude, longitude, baro_altitude\r\nFROM aeronefs\r\nWHERE icao24 = '$var_icao24' \r\n  AND time_position >= TO_TIMESTAMP($__timeFrom(), 'YYYY-MM-DD\"T\"HH24:MI:SS.USSTZD')AT TIME ZONE 'UTC' + INTERVAL '4 hours'\r\n  AND time_position <= TO_TIMESTAMP($__timeTo(), 'YYYY-MM-DD\"T\"HH24:MI:SS.USSTZD')AT TIME ZONE 'UTC' + INTERVAL '4 hours'\r\n\r\n"
    }
   ]
  },
  {
   "title": "Altitude barométrique en fonction du temps ",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "lengthm" } },
   "targets": [
    {
     "rawSql": "select baro_altitude, time_position AT TIME ZONE 'Europe/Paris' AS time_position\r\nfrom aeronefs\r\nwhere icao24 = '$var_icao24'"
    }
   ]
  },
  {
   "title": "Vitesse en m/s en fonction du temps ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "velocityms" } },
   "targets": [
    {
     "rawSql": "select velocity, time_position AT TIME ZONE 'Europe/Paris' AS time_position\r\nfrom aeronefs\r\nwhere icao24 = '$var_icao24'"
    }
   ]
  }
 ]
}