{
 "title": "Suivi Aeronefs Monde Temps Reel Par Categorie",
 "time": { "from": "2023-09-22T10:37:44.953Z", "to": "2023-09-22T22:37:44.953Z" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "categories",
    "label": "Catégories",
    "query": "SELECT lib_category\nFROM aeronefs a\nLEFT JOIN category c on a.category = c.id_category\nWHERE id_insertion = (SELECT MAX(id_insertion) FROM aeronefs) \n\tAND latitude is not null \n\tAND longitude is not null\nGROUP BY lib_category\nHAVING COUNT(*) > 0\norder by COUNT(*) DESC\n"
   }
  ]
 },
 "panels": [
  {
   "title": "Position actuel des aéronefs",
   "type": "geomap",
   "gridPos": { "h": 17, "w": 13, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT icao24, latitude, longitude\r\nFROM aeronefs a\r\nLEFT JOIN category c on a.category = c.id_category\r\nWHERE lib_category = ANY(string_to_array('${categories:raw}', ',')::text[])\r\n  AND id_insertion = (SELECT MAX(id_insertion) FROM aeronefs) \r\n\tAND latitude is not null \r\n\tAND longitude is not null;\r\n"
    }
   ]
  },
  {
   "title": "Date de mesure",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 13, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT TO_CHAR(MAX(date_insertion), 'DD/MM/YYYY HH24:MI:SS') AS date\r\nFROM insertion;\r\n"
    }
   ]
  },
  {
   "title": "Nombre d'aéronefs",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 17, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select count(icao24)\r\nfrom aeronefs a\r\nLEFT JOIN category c on a.category = c.id_category\r\nwhere lib_category = ANY(string_to_array('${categories:raw}', ',')::text[])\r\n\tAND id_insertion = (SELECT MAX(id_insertion) FROM aeronefs) \r\n\tAND latitude is not null \r\n\tAND longitude is not null;"
    }
   ]
  },
  {
   "title": "Moyenne alt baro",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "lengthm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT AVG(baro_altitude)\r\nFROM aeronefs a\r\nLEFT JOIN category c on a.category = c.id_category\r\nWHERE lib_category = ANY(string_to_array('${categories:raw}', ',')::text[])\r\n  AND id_insertion = (SELECT MAX(id_insertion) FROM aeronefs) \r\n\tAND latitude is not null \r\n\tAND longitude is not null;\r\n"
    }
   ]
  },
  {
   "title": "V moyenne",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "velocitykmh" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select AVG(velocity)*3.6\r\nfrom aeronefs a\r\nLEFT JOIN category c on a.category = c.id_category\r\nwhere lib_category = ANY(string_to_array('${categories:raw}', ',')::text[])\r\n\tAND id_insertion = (SELECT MAX(id_insertion) FROM aeronefs) \r\n\tAND latitude is not null \r\n\tAND longitude is not null;"
    }
   ]
  },
  {
   "title": "Répartition nombre aéronef par catégorie",
   "type": "marcusolsson-treemap-panel",
   "gridPos": { "h": 11, "w": 11, "x": 13, "y": 6 },
   "targets": [
    {
     "rawSql": "SELECT lib_category, count(*) as nb\r\nFROM aeronefs a\r\nLEFT JOIN category c on a.category = c.id_category\r\nWHERE id_insertion = (SELECT MAX(id_insertion) FROM aeronefs) \r\n\tAND latitude is not null \r\n\tAND longitude is not null\r\n\tAND c.id_category not in (0,1)\r\nGROUP BY lib_category\r\n"
    }
   ]
  }
 ]
}